/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Reservation {
  'id' : ReservationId,
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'createdAt' : bigint,
  'time' : string,
  'email' : string,
  'partySize' : bigint,
  'phone' : string,
}
export type ReservationId = bigint;
export interface ReservationInput {
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'time' : string,
  'email' : string,
  'partySize' : bigint,
  'phone' : string,
}
export type SubmitResult = { 'ok' : ReservationId } |
  { 'err' : string };
export interface _SERVICE {
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'submitReservation' : ActorMethod<[ReservationInput], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];