/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReservationId = IDL.Nat;
export const Reservation = IDL.Record({
  'id' : ReservationId,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
});
export const ReservationInput = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({
  'ok' : ReservationId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'submitReservation' : IDL.Func([ReservationInput], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReservationId = IDL.Nat;
  const Reservation = IDL.Record({
    'id' : ReservationId,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const ReservationInput = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : ReservationId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'submitReservation' : IDL.Func([ReservationInput], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };